### ISSUE TITLE
Node Configuration Schema

### ISSUE THREAD

**Issue by cafca** [p2panda/handbook#122]
## Summary

_Node operators are users who run and operate a node._

The node configuration schema is an application schema that allows node operators to configure nodes by publishing a configuration via p2panda and assigning it to a node. 

## Description

First, a _node configuration_ is published by the node operator or any other user. It contains configuration settings that control how a node operates. Then, the node operator publishes a _node configuration assigment_, which assigns a specific node to a node configuration. The assignment is based on the node's public key, which must be generated by the node when it is first started and displayed to the node operator. 

 Node implementations allow node operators to configure a specific public key who is authorised to set node configurations for a node installation, this is called the _node operator key_. It may be configured by setting an environment variable that can be read by the node once it starts. 

Once such a node materialises a node configuration instance that was published by its node operator key it updates its own configuration to reflect the new settings. If no node configuration has been assigned to a node, that node uses a _default setting_ for every required configuration option.

### `discovery_mDNS`

Set true to enable mDNS discovery.

- type: `boolean`
- required: yes
- default: true

### `discovery_manual`

Whitespace-separated list of IPs of other nodes to replicate with.

- type: `string`
- required: no

### `owner`

Sets a key group that can change the node's configuration.

- type: `author_relation(KeyGroup)`
- required: no

### Replication by Schema

By default a node doesn't replicate any other node's data. This option sets 
schemas that should be replicated. When a schema is defined here, the node will
try and replicate all logs on all nodes it connects to that store data from that
schema. It will also replicate dependencies of that schema.

- type: reverse relation from Node Configuration: Schema 
- required: no

### Replication by Public Key

This option sets public keys that should be replicated. When a public key is 
defined here, the node will replicate all logs from this public key and their dependencies.

- type: reverse relation from Node Configuration: Public Key
- required: no

## Schemas

Configuration settings that contain lists are represented by additional schemas listed below.

_Note: it would actually be really nice to have a list field type lol_

### Node Configuration

```yaml
name: node configuration
description: contains settings for a p2panda node's configuration options
fields:
  discovery_mDNS: boolean
  discovery_manual: string
  '? owner': author_relation(KeyGroup)
```

### Node Configuration Assignment

```yaml
name: node configuration assignment
description: links specific nodes to a node configuration assignment
fields:
  # link to a previously published node configuration
  node_configuration: relation(node configuration)
  # the node's hex encoded public key
  node_public_key: string
  # Optionally set an owner key group of this node (different from the owner of the configuration)
  '? owner': author_relation(KeyGroup)
```

### Node Configuration: Schema

```yaml
name: node configuration option for schema replication
description: adds schemas to be replicated to a node configuration
fields:
  schema: relation(application schema)
  # link to a previously published node configuration
  node_configuration: author_relation(node configuration)
```

### Node Configuration: Public Key

```yaml
name: node configuration options for public key replication
description: adds public keys whose complete logs + payloads should be replicated to a node configuration
fields:
  public_key: string
  # link to a previously published node configuration
  node_configuration: author_relation(node configuration)
```
