### ISSUE TITLE
How to indicate that an application schema requires pinned / unpinned relations

### ISSUE THREAD

**Issue by adzialocha** [p2panda/handbook#157]
The specification reads that developers can _choose_ if a relation or relation list in their application schema should be using _only_ pinned or _only_ unpinned relations. See: https://github.com/p2panda/handbook/blob/main/website/docs/01-writing-data/schemas.md#relation-fields

Currently we have two different field types: `relation` and `relation_list` which can be both pinned and unpinned. There are two ways we could restrict this:

1. Introduce a boolean for relation field types in `schema_field_v1` to specify the mode. This would then lead to a CDDL which will only allow / disallow relations of certain kind:
    ```yaml
    action: create
    schema: "schema_field_v1"
    version: 1
    fields:
      name: ..
      description: ...
      field_type:
        type: str
        value: "relation" # or "relation_list"
      pinned:
        type: bool
        value: true
    ```

2. Introduce a new operation value type like `pinned_relation` and `pinned_relation_list`:

    ```yaml
    <name>: {
      type: "pinned_relation"
      value: [...]
    }
    
    <name>: {
      type: "pinned_relation_list"
      value: [[...], [...]]
    }
    ```
    
    In the "schema_field_v1" operation one could then explicitly set the field type to what is desired:
    
    ```yaml
    action: create
    schema: "schema_field_v1"
    version: 1
    fields:
      name: ..
      description: ...
      field_type:
        type: str
        value: "pinned_relation" # or "pinned_relation_list"
    ```
