### ISSUE TITLE
How to define the schema id of a relation?

### ISSUE THREAD

**Issue by adzialocha** [p2panda/handbook#160]
In schema field definitions we can define relation fields, for example:

```yaml
action: create | update | delete
version: 1
schema: "schema_field_definition_v1"
fields:
  name: 
    type: str
    value: "profile_picture"
  description: ...
  field_type:
    type: str
    value: "relation"
```

.. but how do we define the schema which needs to be fullfilled by the referrered document?
