### ISSUE TITLE
Untagged operation fields format

### ISSUE THREAD

**Issue by adzialocha** [p2panda/handbook#193]
Before:

```toml
action = "create"
version = 1
schema = "schema_field_definition_v1"

[fields.name]
type = "str"
value = "name"

[fields.type]
type = "str"
value = "str"
```

After:

```toml
action = "create"
version = 1
schema = "schema_field_definition_v1"

[fields]
name = "name"
type = "str"
```
